### ISSUE TITLE
Package name standarization

### ISSUE THREAD

**Issue by fbricker** [openfl/extension-amazonads#1]
Hi, I was about to begin to develop an extension for Amazon Ads, and I just saw yours :+1: 
So, thanks!
Anyway, I've noticed that the package name is still not standardized to extension.ads (same for extension and library name).
If you want, I volunteer for this task :) - I've already done that on some extensions, and I'll begin to do this on some more this week.

Thanks!

**Comment by pozirk** [comment]
Great idea, I had not time to do standardization, so thanks a lot!

**Comment by fbricker** [comment]
Great, I'm working on it :+1: 
I'm also working on one new extension that will manage AdMob, Amazon and Facebook ads using a unified API (using this extension, you only need to call showBanner, hideBanner, showInterstitial, from a single static class). Then, you can switch from ad network without touching your code.

Right now I've integrated Amazon and AdMob. When I have one or two more working and tested on real games, I'll pass this extension to OpenFL as well.

Thanks!

**Comment by pozirk** [comment]
Such extension is really great idea, if you need any help, let me know!
Also, are you planing to add iOS support?

**Comment by fbricker** [comment]
Yes... so far it works with:
AdMob for iOS
AdMob for Android
AmazonAds for Android

My idea is to add:
iAd for iOS
Facebook Ads for Android
Facebook Ads for iOS

Then, we'll see what's next (I'm trying to find some for BlackBerry, but we'll need to change some parts of Lime first to allow cascades on blackberry)

**Comment by fbricker** [comment]
Done :) Please let me know if you don't agree on the changes I've made.
